name: Android Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/android-test.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  x64-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
           - { os: android, arch: aarch64 }
           - { os: android, arch: armv7 }
    steps:
      - uses: actions/checkout@v4

      - name: docker
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Android NDK
        if: ${{ matrix.os == 'android' }}
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r24
          add-to-path: true

      - name: clone
        run: |
          git clone https://codeberg.org/schilytools/schilytools.git schilytools

      - name: android patch
        if: ${{ matrix.os == 'android' }}
        run: |
          git clone https://github.com/termux-user-repository/tur.git tur
          cd schilytools
          for patch in ../tur/tur-on-device/schilytools/*.patch; do
            echo "applying ${patch}"
            git apply "${patch}"
          done

      - name: android make
        if: ${{ matrix.os == 'android' }}
        run: |
          cd schilytools
          CONFIG_RMTCALL="`pwd`/conf/runrmt_ssh"
          CONFIG_RMTHOST="test"
          CONFIG_RMTDEBUG="true"
          CONFIG_RMTCALL=":"
          export CONFIG_RMTCALL
          export CONFIG_RMTHOST
          export CONFIG_RMTDEBUG
          export CONFIG_RMTCALL
          mkdir ~/.ssh
          cat > ~/.ssh/config << EOF 
          Host test
              HostName 127.0.0.1
              User root
              Port 8022
          EOF
          cd psmake
          sh ./MAKE-all
          cd ..
          if [ "${{ matrix.arch }}" = 'aarch64' ]; then
            # x64 android-aarch64
            docker run -d --platform linux/arm64 \
              -p 8022:22 \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y openssh-server && \
                       sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
                       sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
                       passwd -d && \
                       systemctl restart sshd"
            NDK=${ANDROID_NDK_ROOT}
            SYSROOT=\${NDK}/toolchains/llvm/prebuilt/linux-x86_64/sysroot
            CC="\${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang --sysroot=\${SYSROOT}"
            export NDK
            export SYSROOT
            export CC
            ./psmake/smake ARCH=aarch64 OSNAME=linux CCOM=clang "CC_COM=$CC"
            ./psmake/smake install INS_BASE=../build/debug INS_RBASE=../build/debug
            ./psmake/smake install STRIPFLAGS=-s INS_BASE=../build/release INS_RBASE=../build/release
          elif [ "${{ matrix.arch }}" = 'armv7' ]; then
            # x64 android-armv7
            docker run -d --platform linux/arm/v7 \
              -p 8022:22 \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y openssh-server && \
                       sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
                       sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
                       passwd -d && \
                       systemctl restart sshd"
            NDK=${ANDROID_NDK_ROOT}
            SYSROOT=\${NDK}/toolchains/llvm/prebuilt/linux-x86_64/sysroot
            CC="\${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang --sysroot=\${SYSROOT}"
            export NDK
            export SYSROOT
            export CC
            ./psmake/smake ARCH=armv7 OSNAME=linux CCOM=clang "CC_COM=$CC"
            ./psmake/smake install INS_BASE=../build/debug INS_RBASE=../build/debug
            ./psmake/smake install STRIPFLAGS=-s INS_BASE=../build/release INS_RBASE=../build/release
          fi

      - name: ls
        run: ls -lR
