name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  x64-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
           - { os: linux, arch: x86_64 }
           #- { os: linux, arch: aarch64 }
           #- { os: linux, arch: armv7 }
           - { os: android, arch: aarch64 }
           - { os: android, arch: armv7 }

    steps:

      - uses: actions/checkout@v4

      - name: Enable KVM group perms
        if: ${{ matrix.os == 'android' }}
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up Android NDK
        if: ${{ matrix.os == 'android' }}
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r24
          add-to-path: true

      - name: Set up JDK 17
        if: ${{ matrix.os == 'android' }}
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        if: ${{ matrix.os == 'android' }}
        uses: android-actions/setup-android@v3

      - name: Install armv7 Android SDK components
        if: ${{ matrix.os == 'android' && matrix.arch == 'armv7' }}
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools"
          sdkmanager --install "platforms;android-24"
          sdkmanager --install "system-images;android-24;default;armeabi-v7a"
          sdkmanager --install "emulator"

      - name: Install aarch64 Android SDK components
        if: ${{ matrix.os == 'android' && matrix.arch == 'aarch64' }}
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools"
          sdkmanager --install "platforms;android-24"
          sdkmanager --install "system-images;android-24;default;arm64-v8a"
          sdkmanager --install "emulator"

      - name: Create armv7 AVD
        if: ${{ matrix.os == 'android' && matrix.arch == 'armv7' }}
        run: |
          echo "no" | avdmanager create avd \
            --force \
            --name test_avd \
            --package "system-images;android-24;default;armeabi-v7a"

      - name: Create aarch64 AVD
        if: ${{ matrix.os == 'android' && matrix.arch == 'aarch64' }}
        run: |
          echo "no" | avdmanager create avd \
            --force \
            --name test_avd \
            --package "system-images;android-24;default;arm64-v8a"

      - name: Start Emulator
        if: ${{ matrix.os == 'android' }}
        run: |
          export ANDROID_AVD_HOME=$HOME/.config/.android/avd
          $ANDROID_SDK_ROOT/emulator/emulator \
            -avd test_avd \
            -no-window \
            -gpu swiftshader_indirect \
            -noaudio \
            -no-boot-anim \
            -verbose &

          adb wait-for-device

          while [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]; do
            echo "Waiting for emulator to boot..."
            sleep 5
          done
          echo "Emulator is ready"

      - name: docker
        if: ${{ matrix.arch != 'x86_64' && matrix.os != 'android'}}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: clone
        run: |
          git clone https://codeberg.org/schilytools/schilytools.git schilytools

      - name: linux make
        if: ${{ matrix.os == 'linux' }}
        run: |
          if [ "${{ matrix.arch }}" = 'x86_64' ]; then
          # x64 x64
            sudo apt-get update
            sudo apt-get install -y make gcc build-essential
            cd schilytools
            cd psmake
            sh ./MAKE-all
            cd ..
            ./psmake/smake 
            ./psmake/smake install INS_BASE=../build INS_RBASE=../build
          elif [ "${{ matrix.arch }}" = 'armv7' ]; then
            # x64 linux-armv7
            docker run --rm --platform linux/arm/v7 \
              -v $PWD/schilytools:/src \
              -w /src \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y make gcc build-essential && \
                       cd psmake && \
                       sh ./MAKE-all && \
                       cd .. && \
                       ./psmake/smake && \
                       ./psmake/smake install INS_BASE=../build INS_RBASE=../build && \
                       chown -R $(id -u):$(id -g) ./build"
          elif [ "${{ matrix.arch }}" = 'aarch64' ]; then
            # x64 linux-aarch64
            docker run --rm --platform linux/arm64 \
              -v $PWD/schilytools:/src \
              -w /src \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y make gcc build-essential && \
                       cd psmake && \
                       sh ./MAKE-all && \
                       cd .. && \
                       ./psmake/smake && \
                       ./psmake/smake install INS_BASE=../build INS_RBASE=../build && \
                       chown -R $(id -u):$(id -g) ./build"
          fi

      - name: android make
        if: ${{ matrix.os == 'android' }}
        run: |
          cd schilytools
          sed -i 's|rmt=$HOME/android-sdk-linux_x86/platform-tools/adb|rmt=$ANDROID_SDK_ROOT/platform-tools/adb|' "`pwd`/conf/runrmt_android"
          CONFIG_RMTCALL="`pwd`/conf/runrmt_android"
          CONFIG_RMTHOST="127.0.0.1"
          export CONFIG_RMTCALL
          export CONFIG_RMTHOST
          cd psmake
          sh ./MAKE-all
          cd ..
          if [ "${{ matrix.arch }}" = 'aarch64' ]; then
            # x64 android-aarch64
            export CC="${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang --sysroot=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
            ./psmake/smake ARCH=aarch64 OSNAME=linux CCOM=clang "CC_COM=$CC"
            # STRIPFLAGS=-s
            ./psmake/smake install INS_BASE=../build INS_RBASE=../build
          elif [ "${{ matrix.arch }}" = 'armv7' ]; then
            # x64 android-armv7
            export CC="${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang --sysroot=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
            ./psmake/smake ARCH=armv7 OSNAME=linux CCOM=clang "CC_COM=$CC"
            # STRIPFLAGS=-s
            ./psmake/smake install INS_BASE=../build INS_RBASE=../build
          fi

      - name: ls
        run: ls -lR

      - name: push
        run: |
          cd ./schilytools/build || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "${{ matrix.os }}-${{ matrix.arch }}"
          git add .
          git commit -m build
          git remote add origin "https://${{ github.actor }}:${{ secrets.github_token }}@github.com/${{ github.repository }}"
          git push -f -u origin "${{ matrix.os }}-${{ matrix.arch }}"

  arm64-build:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        include:
           - { os: linux, arch: aarch64 }
           - { os: linux, arch: armv7 }
           # - { os: android, arch: aarch64 }
           # - { os: android, arch: armv7 }

    steps:

      - uses: actions/checkout@v4

      - name: docker
        if: ${{ matrix.arch != 'aarch64' && matrix.os != 'android' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: clone
        run: |
          git clone https://codeberg.org/schilytools/schilytools.git schilytools

      - name: linux make
        if: ${{ matrix.os == 'linux' }}
        run: |
          if [ "${{ matrix.arch }}" = 'aarch64' ]; then
            sudo apt-get update
            sudo apt-get install -y make gcc build-essential
            cd schilytools
            cd psmake
            sh ./MAKE-all
            cd ..
            ./psmake/smake 
            ./psmake/smake install INS_BASE=../build INS_RBASE=../build
          elif [ "${{ matrix.arch }}" = 'armv7' ]; then
            # aarch64 linux-armv7
            docker run --rm --platform linux/arm/v7 \
              -v $PWD/schilytools:/src \
              -w /src \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y make gcc build-essential && \
                       cd psmake && \
                       sh ./MAKE-all && \
                       cd .. && \
                       ./psmake/smake && \
                       ./psmake/smake install INS_BASE=../build INS_RBASE=../build && \
                       chown -R $(id -u):$(id -g) ./build"
          fi

      - name: android make
        if: ${{ matrix.os == 'android' }}
        run: |
          if [ "${{ matrix.arch }}" = 'aarch64' ]; then
            # aarch64 android-aarch64
            docker run --rm \
              -v $PWD/schilytools:/src \
              -w /src \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y make gcc build-essential && \
                       cd psmake && \
                       sh ./MAKE-all && \
                       cd .. && \
                       ./psmake/smake && \
                       ./psmake/smake install INS_BASE=../build INS_RBASE=../build && \
                       chown -R $(id -u):$(id -g) ./build"
          elif [ "${{ matrix.arch }}" = 'armv7' ]; then
            # aarch64 android-armv7
            docker run --rm --platform linux/arm/v7 \
              -v $PWD/schilytools:/src \
              -w /src \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y make gcc build-essential && \
                       cd psmake && \
                       sh ./MAKE-all && \
                       cd .. && \
                       ./psmake/smake && \
                       ./psmake/smake install INS_BASE=../build INS_RBASE=../build && \
                       chown -R $(id -u):$(id -g) ./build"
          fi

      - name: ls
        run: ls -lR

      - name: push
        run: |
          cd ./schilytools/build || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "${{ matrix.os }}-${{ matrix.arch }}"
          git add .
          git commit -m build
          git remote add origin "https://${{ github.actor }}:${{ secrets.github_token }}@github.com/${{ github.repository }}"
          git push -f -u origin "${{ matrix.os }}-${{ matrix.arch }}"
