name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  x64-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
           - { os: linux, arch: x86_64 }
           #- { os: linux, arch: aarch64 }
           #- { os: linux, arch: armv7 }
           # - { os: android, arch: aarch64 }
           # - { os: android, arch: armv7 }

    steps:

      - uses: actions/checkout@v4

      - name: android NDK
        if: ${{ matrix.os == 'android' }}
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29
          add-to-path: true

      - name: docker
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: clone
        run: |
          git clone https://codeberg.org/schilytools/schilytools.git schilytools

      - name: linux make
        if: ${{ matrix.os == 'linux' }}
        run: |
          if [ "${{ matrix.arch }}" = 'x86_64' ]; then
          # x64 x64
            sudo apt-get update
            sudo apt-get install -y make gcc build-essential
            cd schilytools
            cd psmake
            sh ./MAKE-all
            cd ..
            ./psmake/smake 
            ./psmake/smake install INS_BASE=../build INS_RBASE=../build
          elif [ "${{ matrix.arch }}" = 'armv7' ]; then
          # x64 linux-armv7
            docker run --rm --platform linux/arm/v7 \
              -v $PWD/schilytools:/src \
              -w /src \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y make gcc build-essential && \
                       cd psmake && \
                       sh ./MAKE-all && \
                       cd .. && \
                       ./psmake/smake && \
                       ./psmake/smake install INS_BASE=../build INS_RBASE=../build && \
                       chown -R $(id -u):$(id -g) ./build"
          elif [ "${{ matrix.arch }}" = 'aarch64' ]; then
          # x64 linux-aarch64
            docker run --rm --platform linux/arm64 \
              -v $PWD/schilytools:/src \
              -w /src \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y make gcc build-essential && \
                       cd psmake && \
                       sh ./MAKE-all && \
                       cd .. && \
                       ./psmake/smake && \
                       ./psmake/smake install INS_BASE=../build INS_RBASE=../build && \
                       chown -R $(id -u):$(id -g) ./build"
          fi

      - name: android make
        if: ${{ matrix.os == 'android' }}
        run: |
          if [ "${{ matrix.arch }}" = 'aarch64' ]; then
          # x64 android-aarch64
          elif [ "${{ matrix.arch }}" = 'armv7' ]; then
          # x64 android-armv7
          fi

      - name: ls
        run: ls -lR

      - name: push
        run: |
          cd ./schilytools/build || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "${{ matrix.os }}-${{ matrix.arch }}"
          git add .
          git commit -m build
          git remote add origin "https://${{ github.actor }}:${{ secrets.github_token }}@github.com/${{ github.repository }}"
          git push -f -u origin "${{ matrix.os }}-${{ matrix.arch }}"

  arm64-build:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        include:
           - { os: linux, arch: aarch64 }
           - { os: linux, arch: armv7 }
           - { os: android, arch: aarch64 }
           - { os: android, arch: armv7 }

    steps:

      - uses: actions/checkout@v4

      - name: docker
        if: ${{ matrix.arch != 'aarch64' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: clone
        run: |
          git clone https://codeberg.org/schilytools/schilytools.git schilytools

      - name: linux make
        if: ${{ matrix.os == 'linux' }}
        run: |
          if [ "${{ matrix.arch }}" = 'aarch64' ]; then
            sudo apt-get update
            sudo apt-get install -y make gcc build-essential
            cd schilytools
            cd psmake
            sh ./MAKE-all
            cd ..
            ./psmake/smake 
            ./psmake/smake install INS_BASE=../build INS_RBASE=../build
          elif [ "${{ matrix.arch }}" = 'armv7' ]; then
          # aarch64 linux-armv7
            docker run --rm --platform linux/arm/v7 \
              -v $PWD/schilytools:/src \
              -w /src \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y make gcc build-essential && \
                       cd psmake && \
                       sh ./MAKE-all && \
                       cd .. && \
                       ./psmake/smake && \
                       ./psmake/smake install INS_BASE=../build INS_RBASE=../build && \
                       chown -R $(id -u):$(id -g) ./build"
          fi

      - name: android make
        if: ${{ matrix.os == 'android' }}
        run: |
          if [ "${{ matrix.arch }}" = 'aarch64' ]; then
          # aarch64 android-aarch64
            docker run --rm \
              -v $PWD/schilytools:/src \
              -w /src \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y make gcc build-essential && \
                       cd psmake && \
                       sh ./MAKE-all && \
                       cd .. && \
                       ./psmake/smake CFLAGS='-static' LDFLAGS='-static' && \
                       ./psmake/smake install INS_BASE=../build INS_RBASE=../build && \
                       chown -R $(id -u):$(id -g) ./build"
          elif [ "${{ matrix.arch }}" = 'armv7' ]; then
          # aarch64 android-armv7
            docker run --rm --platform linux/arm/v7 \
              -v $PWD/schilytools:/src \
              -w /src \
              ubuntu:latest \
              bash -c "apt-get update && \
                       apt-get install -y make gcc build-essential && \
                       cd psmake && \
                       sh ./MAKE-all && \
                       cd .. && \
                       ./psmake/smake CFLAGS='-static' LDFLAGS='-static' && \
                       ./psmake/smake install INS_BASE=../build INS_RBASE=../build && \
                       chown -R $(id -u):$(id -g) ./build"
          fi

      - name: ls
        run: ls -lR

      - name: push
        run: |
          cd ./schilytools/build || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "${{ matrix.os }}-${{ matrix.arch }}"
          git add .
          git commit -m build
          git remote add origin "https://${{ github.actor }}:${{ secrets.github_token }}@github.com/${{ github.repository }}"
          git push -f -u origin "${{ matrix.os }}-${{ matrix.arch }}"
