name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  x64-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
           - { os: linux, arch: x86_64 }
           - { os: linux, arch: armv7 }
           - { os: android, arch: aarch64 }
           - { os: android, arch: armv7 }

    steps:

      - uses: actions/checkout@v4

      - name: android NDK
        if: ${{ matrix.os == 'android' }}
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29
          add-to-path: true

      - name: clone
        run: |
          git clone https://codeberg.org/schilytools/schilytools.git schilytools

      - name: linux make
        if: ${{ matrix.os == 'linux' }}
        run: |
          cd schilytools
          if [ "${{ matrix.arch }}" = 'x86_64' ]; then
            make
            make install INS_BASE=../build INS_RBASE=../build
          elif [ "${{ matrix.arch }}" = 'armv7' ]; then
            make ARCH=armv7 OSNAME=linux
            make install INS_BASE=../build INS_RBASE=../build
          fi

      - name: android make
        if: ${{ matrix.os == 'android' }}
        run: |
          cd schilytools
          export CONFIG_RMTCALL="`pwd`/conf/runrmt_android"
          export CONFIG_RMTHOST="NONE"
          if [ "${{ matrix.arch }}" = 'aarch64' ]; then
            export CC="${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang --sysroot=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
            make ARCH=armv8 OSNAME=linux CCOM=gcc "CC_COM=$CC"
            make install INS_BASE=../build INS_RBASE=../build
          elif [ "${{ matrix.arch }}" = 'armv7' ]; then
            export CC="${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi34-clang --sysroot=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
            make ARCH=armv7 OSNAME=linux CCOM=gcc "CC_COM=$CC"
            make install INS_BASE=../build INS_RBASE=../build
          fi

      - name: ls
        run: ls -R

      - name: push
        run: |
          cd ./schilytools/build || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "${{ matrix.os }}-${{ matrix.arch }}"
          git add .
          git commit -m build
          git remote add origin "https://${{ github.actor }}:${{ secrets.github_token }}@github.com/${{ github.repository }}"
          git push -f -u origin "${{ matrix.os }}-${{ matrix.arch }}"
